### ISSUE TITLE
psc-package doesn't work on Win 8.1

### ISSUE THREAD

**Issue by Boscop** [joneshf/node-psc-package-bin#1]
I installed everything with `npm install -g purescript pulp psc-package` but psc-package isn't working, why?
```
> psc-package --help
events.js:160
      throw er; // Unhandled 'error' event
      ^
 
Error: spawn C:\Users\me\AppData\Roaming\npm\node_modules\psc-package\vendor\psc-package.exe ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```
I also tried reinstalling (running the command again) but it didn't help.

**Comment by joneshf** [comment]
Sorry, I'm not sure. I can look into this in a while. But, I don't have a windows computer so it might not be very productive.

**Comment by Boscop** [comment]
Thanks :)

**Comment by starper** [comment]
I have the same error. Replacing `ignore: ['psc-package']` with `ignore: [bin.use()]` fixes it.

**Comment by joneshf** [comment]
Thanks! That seems straight-forward. I'm unsure how to fix this retroactively though. As far as I know, the version that's on npm can't be changed. Is there a way to do that, or will this need a new version?

I think what I might do is simplify all of this. I don't relly understand the code, since it was forked from upstream. So maintaining it is kind of hard.

Lemme think about it for a minute.

**Comment by starper** [comment]
I don't mind to wait for the next `psc-package` release, so that versions of this two packages were in sync, current version of `psc-package` doesn't work on my machine anyway (because of [34](https://github.com/purescript/psc-package/issues/34))

**Comment by ianbollinger** [comment]
> As far as I know, the version that's on npm can't be changed. Is there a way to do that, or will this need a new version?

That seems to be the case! [Even if you unpublish a particular version, you can't then replace it](https://blog.npmjs.org/post/77758351673/no-more-npm-publish-f).

As for simplifications, one would be removing the last of the three tests in the test suite, since it's more or less copy-and-pasted; i.e., it only really tests that `SOURCE_URL` points to a tarball containing the stack executable.

Another simplification is that it seems the code for building an executable via `stack` was separated into the [spawn-stack](https://github.com/shinnn/spawn-stack/) package; using it would allow the elimination of most of the code in this package and many of the dependencies. This is also nice because it seems to provide error messages in the very real case that the user doesn't have `stack` installed on their system.

As an aside, I noticed an interesting design decision about the test harness this package uses. By default, if any test throws an uncaught exception, the entire test suite breaks. I... don't know why anyone would ever want that behavior. Anyway, it's easy enough to avoid if you add the additional 'tape-catch' dependency and import test from 'tape-catch' in place of 'tape'.

**Comment by starper** [comment]
@joneshf `psc-package` `v0.3.3` is released, so, I guess, now you can merge [9](https://github.com/joneshf/node-psc-package-bin/pull/9) and close this issue

**Comment by joneshf** [comment]
Sorry, I've decided not to maintain this repo anymore.

As mentioned in [this comment](https://github.com/purescript/psc-package/issues/100#issuecomment-385868838), I've nothing really driving me to support this code anymore. `psc-package` can distribute its binaries in a way that's easier on its users. And I'm more than happy to transfer ownership of the npm package.
